### ISSUE TITLE
RecyclerViewPager

### ISSUE THREAD

**Issue by jensneuse** [nitrico/MapViewPager#1]
If you're going to show a lot of different markers/pages, have you considered using RecyclerViewPager?
(http://android-arsenal.com/details/1/1622)

Cheers,
Jens

**Comment by nitrico** [comment]
Hi Jens!

yes, I have considered using it but didn't want to add another dependency if not really needed. Anyway, I'll make some experiments with it, the vertical orientation and the fling support could be interesting :)

Thanks for the comment.

**Comment by jensneuse** [comment]
I understand your point of view.
As an alternative you could provide a wrapper/Builder to let the user decide whether to use a ViewPager or the RecyclerViewPager library.

If you build your library to have the core functionality as just interfaces it's up to the implementation to use ViewPager or a different View/Object.

In advance, I've been testing the library due to a simple fact.
You cannot just add or remove pages within any sort of fragment pager adapter.
With RecyclerView this is possible out of the box.

Considering you'd like to add a few markers or delete some, you'll end up "recreating" the fragment pager adapter because it doesn't support removing a page out of the box.

Cheers,
Jens

**Comment by nitrico** [comment]
I'll give it a try and let you know.

**Comment by nitrico** [comment]
I have it working already (without the possibility of adding and removing items) but I had to create interfaces for the pager, for the adapter, dealing with each kind of listener...

It would be possible to create an interface MapProvider as well, to use another maps service. But, again, it would need to make interfaces for Marker's, CameraPosition's, etc. and not so many devs use another map service.

As I think the main purpose of the library is to show info about positions and not adding or removing them on the fly, I'll leave it as is for now, and maybe add it in a future release.
