### ISSUE TITLE
Fragment Freeze

### ISSUE THREAD

**Issue by Gamis214** [nitrico/MapViewPager#3]
Hi.. this frame is great but i have a work where i put 16 coordenates and the fragment freeze :( i try with:

mvp.getViewPager().setOffscreenPageLimit(limit);

but the pager dont respond... please tell me how i resolve this :( i love this frame and i dont want use other form..  

I use the single mapviewpager... :) thanks

**Comment by nitrico** [comment]
I emailed you. Check it :)
